<style scoped>
    #exportBox td, #exportBox th{
        padding: 0.3rem 0;
        height: auto
    }
    #exportBox tr{
        box-shadow: none !important;
    }
    #bodySetting td{
        vertical-align: top !important;
    }
    table td, table th{
        color: var(--neutral-80)
    }
    #receipt-desc th, #receipt-desc td, 
    #receipt-item th, #receipt-item td,
    #receipt-total th, #receipt-total td,
    #receipt-remark th, #receipt-remark td{
        padding: 0.3rem 0 0.3rem 0;
    }
    #receipt-desc th, 
    #receipt-item th, #receipt-item td,
    #receipt-total td:nth-child(1),
    #receipt-remark td{
        text-align: left;
    }
    #receipt-desc td, #receipt-total td:nth-child(2){
        text-align: right;
    }
</style>

<template>
    <div class="row justify-content-center" id="exportBox" ref="exportedBody">
        <div class="col-lg-4 bg-white text-center p-3 text-neutral-80" >
            <div class="card">
                <div class="card-body">
                    <!-- <img :src="`${dataBusiness?.property?.logo?.url}`" class="w-25">
                    <p v-if="dataBusiness" class="small text-muted mt-3">
                        {{dataBusiness?.property?.name}}<br>
                        {{contactBusiness(0)}}<br>
                        {{contactBusiness(3)}}<br>
                        {{dataBusiness?.property?.website}}<br>
                        {{dataBusiness?.property?.address}}
                    </p>
                    <hr> -->
                    <!-- <table class="table" id="receipt-desc">
                        <tr>
                            <th>Bill #</th>
                            <td>{{dataBusiness?.bill?.bill_number}}</td>
                        </tr>
                        <tr>
                            <th>Customer Name</th>
                            <td>{{dataBusiness?.bill?.customer_name}}</td>
                        </tr>
                        <tr>
                            <th>Generated On</th>
                            <td>{{helperFormatDate(dataBusiness?.bill?.created_at, 'dd mmm yyyy')}} {{helperFormatDate(dataBusiness?.bill?.created_at, 'HH:MM')}}</td>
                        </tr>
                        <tr>
                            <th>Generated By</th>
                            <td>{{$store.state.user.name}}</td>
                        </tr>
                        <tr>
                            <th>Applicable Date</th>
                            <td>{{helperFormatDate(dataBusiness?.bill?.created_at, 'dd mmm yyyy')}} {{helperFormatDate(dataBusiness?.bill?.created_at, 'HH:MM')}}</td>
                        </tr>
                        <tr>
                            <th>Room</th>
                            <td>Room Type (Room)</td>
                        </tr>
                    </table> -->
                    <hr>
                    <table class="table" id="receipt-item">
                        <tr>
                            <th colspan="2"> 1</th>
                        </tr>
                        <tr>
                            <th class="pl-3" width="20%">x 1</th>
                            <th class="text-right" width="80%">Rp 2</th>
                        </tr>
                    </table>
                    <hr>
                    <table class="table" id="receipt-total">
                        <tr>
                            <td><h6 class="font-weight-bolder mb-0">Total</h6></td>
                            <td><h6 class="font-weight-bolder mb-0">Rp 500000</h6></td>
                        </tr>
                    </table>
                    <hr>
                </div>
            </div>
        </div>
    </div>
</template>
